### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Raito00** [RapierXbox/ESP32-Sour-Apple#12]
Hi!
Where can be problem?
Error message:
- - - 
sour-apple-esp32.ino:30:3: error: 'esp_fill_random' was not declared in this scope
   30 |   esp_fill_random(&packet[i], 3); // Authentication Tag
      |   ^~~~~~~~~~~~~~~
exit status 1
Compilation error: 'esp_fill_random' was not declared in this scope

- - - 
Device: LOLIN S3 mini

**Comment by RapierXbox** [comment]
Just add this function:
void esp_fill_random(uint8_t* buf, size_t len) {
for(size_t i = 0; i < len; i++) {
buf[i] = random(0, 1000);
}
}

Not all esp's have hardware random number genaration
