### ISSUE TITLE
error function esp_fill_random

### ISSUE THREAD

**Issue by jpcruz88** [RapierXbox/ESP32-Sour-Apple#5]
In my case the esp_fill_random function was not detected and I only generated one with the same name to generate the random numbers

//Add random function
void esp_fill_random(uint8_t* buf, size_t len) {
   for(size_t i = 0; i < len; i++) {
     buf[i] = random(0, 1000);
   }
}

**Comment by RapierXbox** [comment]
try selecting another esp32 board for compiling...or use ur function but it seems to be slower
